spring:
    application:
        name: gateway-web
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]': # 匹配所有请求
                        allowedOrigins: "*" #跨域处理 允许所有的域
                        allowedHeaders: "*" # 允许所有的请求头过来
                        allowedMethods: # 支持的方法
                            - GET
                            - POST
                            - PUT
                            - DELETE
            routes:
                - id: service-user
                  uri: lb://service-user
                  predicates:
                      - Path=/user/**
                  filters:
                      - StripPrefix=1
                - id: service-discuss
                  uri: lb://service-discuss
                  predicates:
                      - Path=/discuss/**
                  filters:
                      - StripPrefix=1
    redis:
        host: 192.168.211.132
        port: 6379

server:
    port: 8001
eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:7001/eureka
    instance:
        prefer-ip-address: true
management:
    endpoint:
        gateway:
            enabled: true
        web:
            exposure:
                include: true
swagger:
    names: discuss,user